version: "3.8"

services:
  integration-test:
    container_name: test
    build:
      context: ../
      dockerfile: integration-test.Dockerfile
    depends_on:
      - previewer
      - fileserver
    environment:
      - PREVIEWER_URL=http://previewer
  fileserver:
    container_name: fileserver
    build: ../fileserver
    ports:
      - '80:80'

  previewer:
    container_name: previewer
    build: ../
    ports:
      - '8080:80'
