name: integration-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose -p integration-tests -f ./deployments/docker-compose.tests.yaml run integration-test